version: "3.1"
services:
  # bestlyg-website:
  #   container_name: bestlyg-website
  #   restart: always
  #   image: nginx
  #   ports:
  #     - 50000:80
  #   volumes:
  #     - ./nginx/docker/spa:/etc/nginx/conf.d
  #     - ./src/website:/var/www/html/
  mongo:
    container_name: bestlyg-mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./databases/bestlyg-data:/bestlyg-data
      # 挂载数据目录
      - ./databases/bestlyg-mongo/db:/data/db
      # 挂载日志目录
      - ./databases/bestlyg-mongo/log:/var/log/mongodb
      # 挂载配置目录
      - ./databases/bestlyg-mongo/config:/etc/mongo
    ports:
      - 27017:27017
    command: mongod
  mongo-express:
    container_name: bestlyg-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 27018:27018
  mysql:
    image: mysql:latest
    container_name: bestlyg-mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./databases/bestlyg-data:/bestlyg-data
      # 挂载数据目录
      - ./databases/bestlyg-mysql:/var/lib/mysql
  adminer:
    container_name: bestlyg-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    container_name: bestlyg-redis
    image: redis:latest
    restart: always
    volumes:
      - ./databases/bestlyg-data:/bestlyg-data
      - ./databases/bestlyg-redis:/data
    ports:
      - 6379:6379
  postgres:
    container_name: bestlyg-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./databases/bestlyg-data:/bestlyg-data
      - ./databases/bestlyg-postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  # bestlyg-server:
  #   container_name: bestlyg-server
  #   #构建容器
  #   build: ./src
  #   image: bestlyg-server
  #   #直接从git拉去
  #   # build: git@github.com:su37josephxia/docker_ci.git#:backend
  #   # 需要链接本地代码时
  #   # volumes:
  #   #   - ./backend:/usr/src/app
  #   ports:
  #     - 50000:10000
  # bestlyg-web:
  #   container_name: bestlyg-web
  #   restart: always
  #   image: nginx
  #   ports:
  #     - 50001:80
  #   volumes:
  #     - ./nginx/web:/etc/nginx/conf.d
  #     - ./src/bestlyg-web:/var/www/html/
  # bestlyg-leetcode:
  #   container_name: bestlyg-leetcode
  #   restart: always
  #   image: nginx
  #   ports:
  #     - 50002:80
  #   volumes:
  #     - ./nginx/docker/mpa:/etc/nginx/conf.d
  #     # - ./static/:/static/
  #     - ./src/bestlyg-leetcode:/var/www/html/
