packages:
    # all packages in direct subdirs of packages/
    - 'packages/**'
    # - 'submodules/**'
    # all packages in subdirs of components/
    # - 'training/**'
    # exclude packages that are inside test directories
    - '!**/node_modules/**'
    - '!**/public/**'
    - 'web3/*'

catalog:
    # ant
    ahooks: ^3.8.4
    antd: ^5.22.7
    '@ant-design/icons': ^5.5.1
    '@ant-design/v5-patch-for-react-19': latest
    '@ant-design/icons-svg': ^4.4.2
    # markdown
    '@mdx-js/react': ^3.0.1
    '@mdx-js/mdx': ^3.1.0
    marked: ^13.0.0
    marked-directive: ^1.0.5
    # modern
    '@modern-js/app-tools': ^2.63.5
    '@modern-js/module-tools': ^2.63.5
    '@modern-js/plugin-tailwindcss': ^2.63.5
    '@modern-js/runtime': ^2.63.5
    '@modern-js/tsconfig': ^2.63.5

    '@types/fs-extra': ^11.0.4
    fs-extra: ^11.2.0

    '@emotion/hash': ^0.9.1
    '@types/doctrine': ^0.0.9
    '@types/echarts': ^4.9.22
    '@types/express': ^5.0.0
    '@types/figlet': ^1.7.0
    '@types/inquirer': ^9.0.7
    '@types/node': ^20.17.10
    '@types/jest': ^29.5.14
    '@types/jsdom': ^21.1.7
    '@types/minimist': ^1.2.5
    '@types/semver': ^7.5.8
    '@types/supertest': ^6.0.2
    '@types/webpack-env': ^1.18.5
    axios: ^1.7.9
    change-case: ^5.4.4
    clsx: ^2.1.1
    chalk: ^5.3.0
    dayjs: ^1.11.13
    cross-env: ^7.0.3
    dotenv: ^16.4.5
    zx: ^8.3.0
    typescript: ^5.7.2
    rimraf: ^6.0.1
    commander: ^11.1.0
    echarts: ^5.6.0

    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0

    '@types/less': ^3.0.7
    less: ^4.2.0

    '@types/ramda': ^0.30.2
    ramda: ^0.30.0

    vite: ^6.0.7
    '@vitejs/plugin-react': ^4.3.4

    zod: ^3.24.1

    prisma: ^6.2.1
    '@prisma/client': ^6.2.1

    jotai: ^2.11.0

    '@types/tapable': ^2.2.7
    tapable: ^2.2.1

    '@types/lodash': ^4.17.13
    '@types/lodash-es': ^4.17.12
    lodash: ^4.17.21
    lodash-es: ^4.17.21