packages:
  - packages/**
  - '!**/node_modules/**'
  - '!**/public/**'
  - web3/*

autoInstallPeers: true

catalog:
  '@ant-design/cssinjs': ^1.23.0
  '@ant-design/icons': ^5.5.1
  '@ant-design/icons-svg': ^4.4.2
  '@ant-design/v5-patch-for-react-19': latest
  '@emotion/hash': ^0.9.1
  '@mdx-js/mdx': ^3.1.0
  '@mdx-js/react': ^3.0.1
  '@prisma/client': ^6.12.0
  '@types/doctrine': ^0.0.9
  '@types/echarts': ^4.9.22
  '@types/express': ^5.0.0
  '@types/fs-extra': ^11.0.4
  '@types/less': ^3.0.7
  '@types/lodash': ^4.17.13
  '@types/lodash-es': ^4.17.12
  '@types/node': ^20.17.10
  '@types/ramda': ^0.30.2
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/semver': ^7.5.8
  '@types/tapable': ^2.2.7
  '@vitejs/plugin-react': ^4.3.4
  ahooks: ^3.8.4
  antd: ^5.26.6
  axios: ^1.7.9
  chalk: ^5.3.0
  change-case: ^5.4.4
  clsx: ^2.1.1
  commander: ^13.1.0
  cross-env: ^7.0.3
  dayjs: ^1.11.13
  dotenv: ^16.4.5
  echarts: ^5.6.0
  eventemitter3: ^5.0.1
  fs-extra: ^11.3.0
  immer: ^10.1.1
  jotai: ^2.12.5
  less: ^4.2.0
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  marked: ^13.0.0
  marked-directive: ^1.0.5
  prisma: ^6.12.0
  ramda: ^0.30.0
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router-dom: ^7.3.0
  rimraf: ^6.0.1
  semver: ^7.6.0
  tapable: ^2.2.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vite: ^7.0.5
  zod: 'catalog:'
  zx: ^8.5.3

dedupePeerDependents: true

nodeMirror:
  - release: https://npmmirror.com/mirrors/node/
  - rc: https://npmmirror.com/mirrors/node-rc/
  - nightly: https://npmmirror.com/mirrors/node-nightly/

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - core-js
  - esbuild
  - nx
  - prisma
  - protobufjs

registry: https://registry.npmmirror.com

resolvePeersFromWorkspaceRoot: true

sharedWorkspaceLockfile: false

strictPeerDependencies: false

useNodeVersion: 20.18.3
