packages:
  # all packages in direct subdirs of packages/
  - 'packages/**'
  - 'submodules/**'
  # all packages in subdirs of components/
  # - 'training/**'
  # exclude packages that are inside test directories
  - '!**/node_modules/**'
  - '!**/public/**'
  - 'web3/*'
