packages:
  # all packages in direct subdirs of packages/
  - 'packages/**'
  # - 'submodules/**'
  # all packages in subdirs of components/
  # - 'training/**'
  # exclude packages that are inside test directories
  - '!**/node_modules/**'
  - '!**/public/**'
  - 'web3/*'

catalog:
  "@ant-design/icons": ^5.5.1
  "@ant-design/icons-svg": ^4.4.2
  "@mdx-js/react": ^3.0.1
  "@modern-js/app-tools": ^2.63.5
  "@modern-js/module-tools": ^2.63.5
  "@modern-js/plugin-tailwindcss": ^2.63.5
  "@modern-js/runtime": ^2.63.5
  "@modern-js/tsconfig": ^2.63.5
  "@emotion/hash": 0.9.1
  "@types/chrome": ^0.0.268
  "@types/doctrine": ^0.0.9
  "@types/echarts": ^4.9.22
  "@types/express": ^5.0.0
  "@types/figlet": ^1.7.0
  "@types/fs-extra": ^11.0.4
  "@types/inquirer": ^9.0.7
  "@types/node": ^20.17.10
  "@types/jest": ^29.5.14
  "@types/jsdom": ^21.1.7
  "@types/less": ^3.0.7
  "@types/lodash": ^4.17.13
  "@types/lodash-es": ^4.17.12
  "@types/lodash.get": ^4.4.9
  "@types/lodash.merge": ^4.6.9
  "@types/minimist": ^1.2.5
  "@types/ramda": ^0.30.2
  "@types/semver": ^7.5.8
  "@types/supertest": ^6.0.2
  "@types/tapable": ^2.2.7
  "@types/webpack-env": ^1.18.5
  "@types/yargs": ^17.0.33
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0
  fs-extra: ^11.2.0

  ahooks: ^3.8.4
  antd: ^5.22.7
  axios: ^1.7.9
  change-case: ^5.4.4
  clsx: ^2.1.1
  chalk: ^5.3.0
  dayjs: ^1.11.13
  cross-env: ^7.0.3

  dotenv: ^16.4.5
  lodash: ^4.17.21
  zx: ^8.3.0
  typescript: ^5.7.2
  rimraf: ^6.0.1
  ramda: ^0.30.0
  commander: ^11.1.0

  echarts: ^5.6.0
  react: ^18.2.0
  react-dom: ^18.2.0