[package]
edition = "2021"
name = "leetcode"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.2.5", features = ["derive"]}
encoding = "0.2.33"
maplit = "1.0.2"
reqwest = { version = "0.11.17", features = ["json"] }
serde = {version = "1.0.160", features = ["derive"]}
serde_derive = "1.0.160"
serde_json = "1.0.96"
tokio = {version = "1.28.0", features = ["full"]}

[[bin]]
name = "lc"
path = "./bin/lc/main.rs"
