[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.23",
    "langchain-deepseek>=0.1.3",
    "loguru>=0.7.3",
    "pydantic>=2.11.3",
]
