[package]
edition = "2021"
name = "point24"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.84"
wee_alloc = {version = "0.4.5", optional = true}

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O3", "-Os"]

[profile.release]
opt-level = "s"
