// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  resume: string;
  'resume-container': string;
  resumeContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
