// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'resume-template1': string;
  resumeTemplate1: string;
}
declare const cssExports: CssExports;
export default cssExports;
