[package]
name = "bestlyg-guess-beads-contract"
version = "1.0.0"
authors = ["bestlyg <bestlyg.com@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
num-bigint = "0.4.3"
serde = "1.0.181"
uint = { version = "0.9.3", default-features = false }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
members = []
