[package]
edition = "2021"
name = "integration-tests"
publish = false
version = "1.0.0"

[dev-dependencies]
anyhow = "1.0"
borsh = "0.9"
maplit = "1.0"
near-units = "0.2.0"
# arbitrary_precision enabled for u128 types that workspaces requires for Balance types
pkg-config = "0.3.1"
serde_json = {version = "1.0", features = ["arbitrary_precision"]}
tokio = {version = "1.18.1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = {version = "0.3.11", features = ["env-filter"]}
workspaces = "0.6.0"

[[example]]
name = "integration-tests"
path = "src/tests.rs"

[dependencies]
serde = "1.0.186"
