[package]
edition = "2021"
name = "idl-check"
version = "0.1.0"
authors = ["liyigang <liyigang@bytedance.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
protobuf = "3.1.0"
protobuf-parse = "3.1.0"
smol = "1.2.5"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
