import { LedgerType } from '@bestlyg/common/prisma-client';

export const ledgerTypeRecord: Record<LedgerType, { label: string; type: LedgerType }> = {
    Generally: { label: '一般', type: 'Generally' },
    Drinks: { label: '酒水饮料', type: 'Drinks' },
    Food: { label: '餐饮', type: 'Food' },
    Transportation: { label: '交通', type: 'Transportation' },
    RedEnvelope: { label: '红包', type: 'RedEnvelope' },
    Taobao: { label: '淘宝', type: 'Taobao' },
    Rent: { label: '房租', type: 'Rent' },
    PhoneBill: { label: '话费', type: 'PhoneBill' },
    DailyNecessities: { label: '生活用品', type: 'DailyNecessities' },
    Drug: { label: '药品', type: 'Drug' },
    BuyGroceries: { label: '买菜', type: 'BuyGroceries' },
    Movie: { label: '电影', type: 'Movie' },
    Snack: { label: '零食', type: 'Snack' },
    Fruit: { label: '水果', type: 'Fruit' },
    ClothesShoesBags: { label: '衣服鞋包', type: 'ClothesShoesBags' },
    SkinMakeup: { label: '护肤彩妆', type: 'SkinMakeup' },
    Salary: { label: '工资', type: 'Salary' },
    FamilyWallet: { label: '小家花钱包', type: 'FamilyWallet' },
    BreakfastWallet: { label: '早餐月月包', type: 'BreakfastWallet' },
    LunchWallet: { label: '中饭菜钱包', type: 'LunchWallet' },
    DinnerWallet: { label: '晚餐小荷包', type: 'DinnerWallet' },
    TravelWallet: { label: '一起环游世界', type: 'TravelWallet' },
};